;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        delete-backward-or-delete-horizontal-space
        helm-exit-minibuffer
        kill-word-or-delete-horizontal-space
        mc/mark-symbol
        my-helm
        mykie:global-map:f:self-insert-command
        mykie:global-map:s:self-insert-command
        seq-copy-thing
        seq-end
        seq-home
        upward-mark-thing
        wdired-next-line
        wgrep-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        cua-delete-region
        dired-jump
        help-for-help
        scroll-down-line
        scroll-up-line
        smex
        ))
